dataset_fn: 'h2o.h5'
P: 64
root_location: .
system: 'h2o'
init_file : ./example_setup/init.xyz
temp_folders: ['0100','300','600']
temperatures: [100, 300, 600]
data_dict: {pos: [simulation.pos, 'coordinates'],  
            for: [simulation.for, 'forces'],
            fsp:  [simulation.fsp, 'forces']}
first_frame: 250
last_frame:  25250
add_spring_energy: False
add_potential_energy: False
recompute_spring_energy: False
potential_energy_file: 'simulation.out'
spring_energy_file: null
