#!/bin/bash
#SBATCH --export=ALL
#SBATCH --job-name=tr_0
#SBATCH --tasks 1
#SBATCH --mem-per-cpu=32G
#SBATCH --time=1-00:10:00
#SBATCH --mail-type=FAIL
#SBATCH --nodes=1
#SBATCH --gres=gpu:rtx2080ti:1
#SBATCH --output=job%j.out
#SBATCH --error=job%j.err
#SBATCH --partition=gpu

source ~/.bashrc
conda activate picg
nvidia-smi
python ${PATH2PIGS}/scripts/pigs-train_h5.py fit  --config trainer.yaml --config mace.yaml 
