output_file: features.npz
position_file: ../../modeling/example_setup/simulation.pos_0.xyz
system: bulk_h2o
analysis_cfg:
        class_path: config.BulkH2OConfig
        init_args:
                d: 19.729499153475388
                n_molecules: 256
                stride: 5
                rdf_params_oo: 
                        class_path: config.RDFConfig
                        init_args:
                                bin_width:  0.01
                                periodic: True
                                r_range: [0.0, 1.0]
                rdf_params_oh:
                        class_path: config.RDFConfig
                        init_args:
                                bin_width: 0.01
                                periodic: True
                                r_range: [0.0, 1.0]
                rdf_params_hh: 
                        class_path: config.RDFConfig
                        init_args:
                                bin_width: 0.01
                                periodic: True 
                                r_range: [0.0, 1.0]
